blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/9AjGBjGp6Q
    about: Questions, ideas, and support
  - name: Support on Patreon
    url: https://www.patreon.com/c/slabworks
    about: Support Arena Coach development
